name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_to_github_page:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{github.workflow}}-${{github.ref}}    
    steps:
      - name: Init checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install  
      
      - name: Build Site
        run: npm run build

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build